<?php

namespace Pushword\AdminBlockEditor\Service;

use Doctrine\ORM\EntityManagerInterface;
use JsonException;
use Pushword\Core\Entity\Media;
use Pushword\Core\Entity\Page;
use Pushword\Core\Repository\MediaRepository;
use Pushword\Core\Utils\MediaFileName;

use function Safe\json_decode;

/**
 * Renames media files from the captions typed in EditorJS Image and Gallery blocks,
 * as long as the media has not been manually renamed (Media::isFileNameAutoGenerated()).
 *
 * The page content is never rewritten: old references keep resolving through
 * Media::fileNameHistory, and name collisions are handled by MediaConflictResolver on flush.
 */
final readonly class MediaCaptionRenamer
{
    public function __construct(
        private EntityManagerInterface $em,
        private MediaRepository $mediaRepository,
    ) {
    }

    public function renameFromContent(Page $page): void
    {
        $renamed = false;

        foreach (self::extractCaptionedMedia($page->getMainContent()) as [$src, $caption]) {
            if ($this->rename($src, $caption)) {
                $renamed = true;
            }
        }

        if ($renamed) {
            $this->em->flush();
        }
    }

    /**
     * Extracts [mediaReference, caption] pairs from page markdown, covering both EditorJS
     * Image blocks (`![caption](src)`) and Gallery blocks (`{{ gallery({"file":"caption"}) }}`).
     *
     * @return list<array{string, string}>
     */
    public static function extractCaptionedMedia(string $content): array
    {
        $pairs = [];

        // Image blocks: ![caption](src) — caption inside [], src up to ) or whitespace (drops a markdown title)
        preg_match_all('/!\[(?<caption>[^\]]*)\]\((?<src>[^)\s]+)/', $content, $images, \PREG_SET_ORDER);
        foreach ($images as $image) {
            $pairs[] = [$image['src'], $image['caption']];
        }

        // Gallery blocks: {{ gallery({"file.jpg":"caption", ...}) }} — media is the key, caption the value
        preg_match_all('/{{ gallery\(\s*(?:images:\s*)?(?<medias>\{.*?\})/s', $content, $galleries, \PREG_SET_ORDER);
        foreach ($galleries as $gallery) {
            try {
                $decoded = json_decode($gallery['medias'], true);
            } catch (JsonException) {
                continue;
            }

            if (! \is_array($decoded)) {
                continue;
            }

            foreach ($decoded as $media => $caption) {
                if (\is_string($media) && \is_string($caption)) {
                    $pairs[] = [$media, $caption];
                }
            }
        }

        return $pairs;
    }

    private function rename(string $src, string $caption): bool
    {
        $caption = trim($caption);
        if ('' === $caption) {
            return false;
        }

        $media = $this->resolveMedia($src);
        // Use the persisted alt, not the live one: MediaExtension syncs alt = caption in
        // memory while rendering content, which would make every captioned media look
        // "manually renamed" and defeat the auto-rename. The persisted alt still reflects
        // the last actual rename, so it correctly tells auto-named from manually-renamed.
        if (! $media instanceof Media || ! $media->isImage() || ! $media->isFileNameAutoGenerated($this->persistedAlt($media))) {
            return false;
        }

        $newSlug = MediaFileName::slugify($caption);
        $currentBase = basename($media->getFileName(), MediaFileName::extractExtension($media->getFileName()));
        if ('' === $newSlug || $newSlug === $currentBase) {
            return false;
        }

        $media->setAlt($caption);
        $media->setSlugForce($caption);

        return true;
    }

    /**
     * The alt as last persisted (Doctrine's original snapshot), ignoring the in-memory
     * caption sync performed by MediaExtension during rendering.
     */
    private function persistedAlt(Media $media): string
    {
        $original = $this->em->getUnitOfWork()->getOriginalEntityData($media);

        return \is_string($original['alt'] ?? null) ? $original['alt'] : $media->getAlt(true);
    }

    private function resolveMedia(string $src): ?Media
    {
        $fileName = $this->extractFileName($src);
        if ('' === $fileName) {
            return null;
        }

        return $this->mediaRepository->findOneByFileNameOrHistory($fileName);
    }

    /**
     * Reduces a markdown image src (`/media/md/photo.jpg`) or a raw gallery key (`photo.jpg`)
     * to a bare filename usable for lookup.
     */
    private function extractFileName(string $src): string
    {
        $path = strtok(urldecode($src), '?#');

        return false === $path ? '' : basename($path);
    }
}
