<?php

namespace Pushword\Core\Tests\Entity;

use PHPUnit\Framework\TestCase;
use Pushword\Core\Entity\Media;

final class MediaTest extends TestCase
{
    public function testBasic(): void
    {
        $media = new Media();
        self::assertEmpty($media->getAlt());

        $media->setAlt('test');
        self::assertSame('test', $media->getAlt());
    }

    public function testGetExtensionReturnsLowercasedExtensionWithoutDot(): void
    {
        $cases = [
            'photo.jpg' => 'jpg',
            'image.jpeg' => 'jpeg',
            'logo.png' => 'png',
            'pic.webp' => 'webp',
            // Normalization keeps the uppercase extension, so getExtension() must
            // lowercase it — the <picture> fallback path depends on it matching the
            // generated (lowercase) cache file.
            'graphic.SVG' => 'svg',
            // No extension yields an empty string (degenerate, never a real image).
            'noextension' => '',
        ];

        foreach ($cases as $fileName => $expected) {
            $media = new Media();
            $media->setFileName($fileName);
            self::assertSame($expected, $media->getExtension(), $fileName);
        }
    }

    public function testSetFileNameNormalizesInput(): void
    {
        $media = new Media();
        $media->setFileName('Voyage sur mesure.jpg');
        self::assertSame('voyage-sur-mesure.jpg', $media->getFileName());
    }

    public function testSetFileNamePreservesAlreadyNormalized(): void
    {
        $media = new Media();
        $media->setFileName('voyage-sur-mesure.jpg');
        self::assertSame('voyage-sur-mesure.jpg', $media->getFileName());
    }

    public function testSetFileNameHandlesAccents(): void
    {
        $media = new Media();
        $media->setFileName('été à Paris.png');
        self::assertSame('ete-a-paris.png', $media->getFileName());
    }

    public function testSetFileNameTracksHistory(): void
    {
        $media = new Media();
        $media->setFileName('first-name.jpg');
        $media->setFileName('Second Name.jpg');
        self::assertSame('second-name.jpg', $media->getFileName());
        self::assertTrue($media->hasFileNameInHistory('first-name.jpg'));
    }

    public function testSetFileNameNull(): void
    {
        $media = new Media();
        $media->setFileName('test.jpg');
        $media->setFileName(null);
        self::assertSame('test.jpg', $media->getFileName());
    }

    public function testIsFileNameAutoGeneratedAfterFreshUpload(): void
    {
        // On upload, alt and fileName are both seeded from the same original name.
        $media = new Media();
        $media->setAlt('image (2)');
        $media->setFileName('image-2.jpg');
        self::assertTrue($media->isFileNameAutoGenerated());
    }

    public function testIsFileNameAutoGeneratedWhenSyncedWithCaption(): void
    {
        $media = new Media();
        $media->setAlt('blue lagoon');
        $media->setFileName('blue-lagoon.jpg');
        self::assertTrue($media->isFileNameAutoGenerated());
    }

    public function testIsFileNameAutoGeneratedFalseAfterManualRename(): void
    {
        // A human renamed the slug independently of the alt: the two diverge.
        $media = new Media();
        $media->setAlt('blue lagoon');
        $media->setFileName('hero-banner.jpg');
        self::assertFalse($media->isFileNameAutoGenerated());
    }

    public function testIsFileNameAutoGeneratedFalseWhenEmpty(): void
    {
        $media = new Media();
        self::assertFalse($media->isFileNameAutoGenerated());
    }

    public function testIsFileNameAutoGeneratedFalseWhenAltEmpty(): void
    {
        // No alt to track: keep the conservative default and never auto-rename.
        $media = new Media();
        $media->setFileName('photo.jpg');
        self::assertFalse($media->isFileNameAutoGenerated());
    }

    public function testHiddenFromAdminDefaultsFalse(): void
    {
        $media = new Media();
        self::assertFalse($media->hiddenFromAdmin);
    }

    public function testHiddenFromAdminCanBeSetTrue(): void
    {
        $media = new Media();
        $media->hiddenFromAdmin = true;
        self::assertTrue($media->hiddenFromAdmin);
    }
}
