<?php

namespace Pushword\Core\Tests\Entity;

use DateTime;
use Exception;
use PHPUnit\Framework\TestCase;
use Pushword\Core\Entity\Media;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Validation;

final class MediaTest extends TestCase
{
    public function testBasic(): void
    {
        $media = new Media();
        self::assertEmpty($media->getAlt());

        $media->setAlt('test');
        self::assertSame('test', $media->getAlt());
    }

    public function testGetExtensionReturnsLowercasedExtensionWithoutDot(): void
    {
        $cases = [
            'photo.jpg' => 'jpg',
            'image.jpeg' => 'jpeg',
            'logo.png' => 'png',
            'pic.webp' => 'webp',
            // Normalization keeps the uppercase extension, so getExtension() must
            // lowercase it — the <picture> fallback path depends on it matching the
            // generated (lowercase) cache file.
            'graphic.SVG' => 'svg',
            // No extension yields an empty string (degenerate, never a real image).
            'noextension' => '',
        ];

        foreach ($cases as $fileName => $expected) {
            $media = new Media();
            $media->setFileName($fileName);
            self::assertSame($expected, $media->getExtension(), $fileName);
        }
    }

    public function testSetFileNameNormalizesInput(): void
    {
        $media = new Media();
        $media->setFileName('Voyage sur mesure.jpg');
        self::assertSame('voyage-sur-mesure.jpg', $media->getFileName());
    }

    public function testSetFileNamePreservesAlreadyNormalized(): void
    {
        $media = new Media();
        $media->setFileName('voyage-sur-mesure.jpg');
        self::assertSame('voyage-sur-mesure.jpg', $media->getFileName());
    }

    public function testSetFileNameHandlesAccents(): void
    {
        $media = new Media();
        $media->setFileName('été à Paris.png');
        self::assertSame('ete-a-paris.png', $media->getFileName());
    }

    public function testSetFileNameTracksHistory(): void
    {
        $media = new Media();
        $media->setFileName('first-name.jpg');
        $media->setFileName('Second Name.jpg');
        self::assertSame('second-name.jpg', $media->getFileName());
        self::assertTrue($media->hasFileNameInHistory('first-name.jpg'));
    }

    public function testSetFileNameNull(): void
    {
        $media = new Media();
        $media->setFileName('test.jpg');
        $media->setFileName(null);
        self::assertSame('test.jpg', $media->getFileName());
    }

    public function testIsFileNameAutoGeneratedAfterFreshUpload(): void
    {
        // On upload, alt and fileName are both seeded from the same original name.
        $media = new Media();
        $media->setAlt('image (2)');
        $media->setFileName('image-2.jpg');
        self::assertTrue($media->isFileNameAutoGenerated());
    }

    public function testIsFileNameAutoGeneratedWhenSyncedWithCaption(): void
    {
        $media = new Media();
        $media->setAlt('blue lagoon');
        $media->setFileName('blue-lagoon.jpg');
        self::assertTrue($media->isFileNameAutoGenerated());
    }

    public function testIsFileNameAutoGeneratedFalseAfterManualRename(): void
    {
        // A human renamed the slug independently of the alt: the two diverge.
        $media = new Media();
        $media->setAlt('blue lagoon');
        $media->setFileName('hero-banner.jpg');
        self::assertFalse($media->isFileNameAutoGenerated());
    }

    public function testIsFileNameAutoGeneratedFalseWhenEmpty(): void
    {
        $media = new Media();
        self::assertFalse($media->isFileNameAutoGenerated());
    }

    public function testIsFileNameAutoGeneratedFalseWhenAltEmpty(): void
    {
        // No alt to track: keep the conservative default and never auto-rename.
        $media = new Media();
        $media->setFileName('photo.jpg');
        self::assertFalse($media->isFileNameAutoGenerated());
    }

    public function testHiddenFromAdminDefaultsFalse(): void
    {
        $media = new Media();
        self::assertFalse($media->hiddenFromAdmin);
    }

    public function testHiddenFromAdminCanBeSetTrue(): void
    {
        $media = new Media();
        $media->hiddenFromAdmin = true;
        self::assertTrue($media->hiddenFromAdmin);
    }

    public function testSetMediaFileTouchesUpdatedAtOnlyWithAFile(): void
    {
        $media = new Media();
        $before = new DateTime('2020-01-01');
        $media->updatedAt = $before;

        $media->setMediaFile();
        self::assertSame($before, $media->getUpdatedAtNullable());

        $media->setMediaFile(new File(__FILE__, false));
        self::assertNotSame($before, $media->getUpdatedAtNullable());
    }

    public function testGetMediaFileNameThrowsWithoutAFile(): void
    {
        $media = new Media();
        $this->expectException(Exception::class);
        $media->getMediaFileName();
    }

    public function testGetMediaFileNameReturnsClientNameForUploads(): void
    {
        $media = new Media();
        $media->setMediaFile(new UploadedFile(__FILE__, 'Original Name.php', null, null, true));
        self::assertSame('Original Name.php', $media->getMediaFileName());

        $media->setMediaFile(new File(__FILE__, false));
        self::assertSame('MediaTest.php', $media->getMediaFileName());
    }

    public function testMimeTypeIsNormalized(): void
    {
        $media = new Media();
        self::assertNull($media->getMimeType());

        $media->setMimeType('image/jpg');
        self::assertSame('image/jpeg', $media->getMimeType());

        $media->setMimeType('image/png');
        self::assertSame('image/png', $media->getMimeType());
    }

    public function testStoreInRequiresProjectDirAndKeepsThePlaceholder(): void
    {
        $media = new Media();
        $this->expectException(Exception::class);
        $media->getStoreIn();
    }

    public function testStoreInSubstitutesProjectDir(): void
    {
        $media = new Media();
        $media->projectDir = '/var/www';
        $media->setStoreIn('/var/www/media/');
        self::assertSame('/var/www/media', $media->getStoreIn());
        self::assertSame('/var/www/media/pic.jpg', $media->setFileName('pic.jpg')->getPath());
    }

    public function testSlugFallsBackToFileNameWithoutExtension(): void
    {
        $media = new Media();
        $media->setFileName('voyage-sur-mesure.jpg');
        self::assertSame('voyage-sur-mesure', $media->getSlug());
    }

    public function testChangingTheSlugRenamesTheFile(): void
    {
        $media = new Media();
        $media->setFileName('old-name.jpg');
        $media->setSlug('old-name');

        $media->setSlugForce('New Name');
        self::assertSame('new-name.jpg', $media->getFileName());
        self::assertTrue($media->hasFileNameInHistory('old-name.jpg'));
    }

    public function testSizeCoercesNullToZero(): void
    {
        $media = new Media();
        self::assertSame(0, $media->size);

        $media->size = 12345;
        self::assertSame(12345, $media->size);

        $media->size = null;
        self::assertSame(0, $media->size);
    }

    public function testFileNameBeforeUpdateKeepsTheFirstValue(): void
    {
        $media = new Media();
        $media->setFileName('first.jpg');
        $media->setFileName('second.jpg');
        $media->setFileName('third.jpg');
        self::assertSame('first.jpg', $media->fileNameBeforeUpdate);
        self::assertSame(['first.jpg', 'second.jpg'], $media->fileNameHistory);
    }

    public function testLicenseStateDefaultsToEmpty(): void
    {
        $media = new Media();
        self::assertSame('', $media->licenseState);

        $media->licenseState = 'seeded';
        self::assertSame('seeded', $media->licenseState);
    }

    /**
     * Replacing the file of an existing media with one bigger than upload_max_filesize:
     * PHP passes an UploadedFile with an empty path, and reading its mime type fatals.
     * The user must get a form error instead of a 500.
     */
    public function testRejectedUploadIsAViolationNotAnException(): void
    {
        $media = new Media();
        $media->setFileName('cairn.jpg');
        $media->setMimeType('image/jpeg');
        $media->setMediaFile(new UploadedFile('', 'too-big.jpg', 'image/jpeg', \UPLOAD_ERR_INI_SIZE, false));

        $violations = Validation::createValidatorBuilder()->enableAttributeMapping()->getValidator()->validate($media);

        self::assertCount(1, $violations);
        self::assertSame('mediaFile', $violations->get(0)->getPropertyPath());
        self::assertStringContainsString('too large', (string) $violations->get(0)->getMessage());
    }
}
