services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $mediaClass: "%pw.entity_media%"
      $pageClass: "%pw.entity_page%"
      $userClass: "%pw.entity_user%"
      $projectDir: "%kernel.project_dir%"
      $filterSets: "%pw.image_filter_sets%"
      $publicMediaDir: "%pw.public_media_dir%"
      $mediaDir: "%pw.media_dir%"
      $rawApps: "%pw.apps%"
      $publicDir: "%pw.public_dir%"
      $pathToBin: "%pw.path_to_bin%"
      $tailwindGeneratorisActive: "%pw.tailwind_generator%"

  Pushword\Core\PushwordCoreBundle: ~

  Pushword\Core\:
    resource: "../../../src/*"
    exclude: "../../../src/{Extension,Repository,DependencyInjection,Entity,Migrations,Tests,Kernel.php}"

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  Pushword\Core\Controller\:
    resource: "../../../src/Controller"
    tags: ["controller.service_arguments"]


  Pushword\Core\Repository\PageRepository:
    arguments:
      $entityClass: "%pw.entity_page%"

  Pushword\Core\Repository\MediaRepository:
    arguments:
      $entityClass: "%pw.entity_media%"

  Pushword\Core\Repository\UserRepository:
    arguments:
      $entityClass: "%pw.entity_user%"

  # --------
  # TWIG extension
  # --------

  Twig\Extension\StringLoaderExtension: ~
  PiedWeb\RenderAttributes\TwigExtension: ~
  Twig\Extra\Intl\IntlExtension: ~


  Pushword\Core\Router\PushwordRouteGenerator:
    public: true # todo limit to test https://stackoverflow.com/questions/54466158/symfony-4-2-how-to-do-a-service-public-only-for-tests


  Pushword\Core\Component\App\AppPool:
    public: true # todo limit to test https://stackoverflow.com/questions/54466158/symfony-4-2-how-to-do-a-service-public-only-for-tests

  Pushword\Core\Service\VichUploadPropertyNamer:
    public: true