#!/bin/sh

php ./.scripts/generate-docs-assets


sh ./.scripts/data-preserve

cd packages/skeleton

php bin/console pushword:flat:import pushword.piedweb.com
php bin/console pushword:static:generate pushword.piedweb.com

cd ../../
sh ./.scripts/data-restore
