#!/bin/bash -e

cd packages/skeleton
rm var/app.db|| true
rm -rf media|| true
cp -r media~ media
php bin/console doctrine:schema:create -q
php bin/console doctrine:fixtures:load -q
php bin/console pushword:image:cache -q
php bin/console pushword:user:create admin@example.tld p@ssword ROLE_SUPER_ADMIN