name: "Static Code Analysis"

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.3]
        stability: [prefer-stable] #prefer-lowest,

    name: PHPStan - P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Install Composer dependencies (highest)
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: highest
          composer-options: --prefer-dist --${{ matrix.stability }} --no-interaction

      - name: Build container
        run: cd packages/skeleton && php ./bin/console cache:clear

      - name: PHPStan
        run: vendor/bin/phpstan --memory-limit=1G analyse --error-format=github --debug
