name: Split Monorepo

on: push

jobs:
  split_monorepo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - core
          - conversation
          - admin
          - flat
          - page-scanner
          - page-update-notifier
          - static-generator
          - template-editor
          - skeleton
          - svg
          - installer
          - js-helper
          - version
          - new
          - admin-block-editor
          - advanced-main-image

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - # get git previous tag
        id: previous_tag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'

      - # Uses an action in the root directory
        name: Monorepo Split of ${{ matrix.package }}
        uses: danharrin/monorepo-split-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'pushword'
          repository_name: '${{ matrix.package }}'
          tag: ${{ steps.previous_tag.outputs.tag }}
          user_name: 'RobinDev'
          user_email: 'contact@piedweb.com'

  test_installer:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger next workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: after-split-monorepo
